server:
  port: 8081

spring:
  application:
    name: aaa123
  datasource:
    url: jdbc:h2:mem:themedb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  jwt:
    secret: your-very-secret-and-very-long-and-very-secure-key-here-123456
    expiration: 86400000 # 24 hours
